# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc
#Edited by Raymond Doetjes

parameters:
  - name: datasource
    displayName: Datasource
    type: string
    default: rdoetjes@test.phonax.com:1433/TST
    values:
    - rdoetjes@test.phonax.com:1433/TST
    - rdoetjes@test.phonax.com:1433/ACC
    - rdoetjes@test.phonax.com:1433/PRD

trigger:
  branches:
    include:
      - dev
      - staging
      - main

pool: 'RaspberryPI'

stages:
  - stage: Build
    displayName: "Build linefollower"
    jobs:
      - job:
        steps:
        #run make clean and make
        - template: makeclean_make.yml
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)/build/apps/'
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
            
        #Only build an artefact for main, not for our feature branches
        - task: PublishBuildArtifacts@1
          condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'linefollower'
            publishLocation: 'Container'

  - stage: DeployDev
    #only run deploy when committed on main.
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    displayName: "Deploy to Dev"
    variables:
      - group: YAML-DEV-VARS
    jobs:
      - deployment:
        environment: 'DEV'
        strategy:
          runOnce:
            deploy:                      
              steps:
                - task: DownloadBuildArtifacts@1
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'linefollower'
                    downloadPath: '$(System.ArtifactsDirectory)'
                
                - task: CopyFiles@2
                  displayName: 'Copy Files to: /home/pi/linefollower/'
                  inputs:
                    SourceFolder: '$(System.DefaultWorkingDirectory)/build/apps'
                    TargetFolder: /home/pi/linefollower/
                    OverWrite: true
