# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: dev
    values:
    - dev
    - tst
    - prd

trigger:
- main
pool: 'ubuntu-latest'

stages:
  - stage: Clean
    displayName: "make clean"
    jobs:
      - job:
        steps:
         - script: |
            make clean
            if [ $? -ne 0 ]; then
                exit 1
            fi

  - stage: Build
    displayName: "make"
    jobs:
      - job:
        steps:
        - script: |
            make
            if [ $? -ne 0 ]; then
                exit 1
            fi
          displayName: "make"
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)/build/apps/'
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'linefollower'
            publishLocation: 'Container'

  - stage: DeployDev
    displayName: "Deploy to Dev"
    jobs:
     - job:
       steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)'
        
        - task: CopyFiles@2
          displayName: 'Copy Files to: /home/pi/linefollower/'
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)/_rdoetjes.linerobot/linefollower/'
            TargetFolder: /home/pi/linefollower/
            OverWrite: true